import { test, expect } from 'playwright/test'
import { assertStoryHealthy, openStory } from './story-ready.mjs'

test.afterEach(async ({ page }) => { await assertStoryHealthy(page) })

for (const theme of ['light', 'dark']) {
  test(`mobile navigation layers and return focus ${theme}`, async ({ page, baseURL }, info) => {
    await openStory(page, 'dashboard-sidebarlayout--desktop', theme, { width: 390, height: 844 }, baseURL)
    const opener = page.getByRole('button', { name: 'Open navigation', exact: true })
    const drawer = page.getByRole('dialog', { name: 'Navigation', exact: true })
    await page.evaluate(() => { document.body.style.overflow = 'auto' })
    await opener.click()
    expect(await page.locator('body').evaluate(node => getComputedStyle(node).overflow)).toBe('hidden')
    const close = drawer.getByRole('button', { name: 'Close navigation', exact: true })
    const account = drawer.getByRole('button', { name: 'User menu', exact: true })
    await expect(close).toBeFocused()
    await page.keyboard.press('Shift+Tab')
    await expect(account).toBeFocused()
    await page.keyboard.press('Tab')
    await expect(close).toBeFocused()
    await account.click()
    const appearance = page.getByRole('menuitem', { name: /Appearance/ })
    await appearance.focus()
    await appearance.press('ArrowRight')
    await expect(page.getByRole('menuitem', { name: 'Light', exact: true })).toBeVisible()
    await page.screenshot({ path: info.outputPath(`navigation-appearance-${theme}.png`), animations: 'disabled' })
    await page.keyboard.press('Escape')
    await expect(page.getByRole('menu')).toHaveCount(0)
    await expect(drawer).toBeVisible()
    await expect(account).toBeFocused()
    await page.keyboard.press('Escape')
    await expect(drawer).toHaveCount(0)
    await expect(opener).toBeFocused()
    expect(await page.locator('body').evaluate(node => getComputedStyle(node).overflow)).toBe('auto')
    await opener.click()
    await close.click()
    await expect(drawer).toHaveCount(0)
    await expect(opener).toBeFocused()
    await opener.click()
    await page.mouse.click(380, 400)
    await expect(drawer).toHaveCount(0)
    await expect(opener).toBeFocused()
    await opener.click()
    await page.screenshot({ path: info.outputPath(`navigation-open-${theme}.png`), animations: 'disabled' })
    // Serve an actual destination so the anchor exercises navigation without
    // asking Storybook's static server to invent a product route.
    await page.route('**/vault', route => route.fulfill({ contentType: 'text/html', body: '<h1>Vault destination</h1>' }))
    await drawer.getByRole('link', { name: 'Vault', exact: true }).click()
    await expect(page).toHaveURL(/\/vault$/)
    await expect(page.getByRole('heading', { name: 'Vault destination' })).toBeVisible()
  })
}

test('desktop keeps its rail and account menu', async ({ page, baseURL }) => {
  await openStory(page, 'dashboard-sidebarlayout--desktop', 'light', { width: 1440, height: 900 }, baseURL)
  await expect(page.getByRole('button', { name: 'Open navigation', exact: true })).toBeHidden()
  await expect(page.getByRole('link', { name: 'Vault', exact: true })).toBeVisible()
  const account = page.getByRole('button', { name: 'User menu', exact: true }).filter({ visible: true })
  await account.click()
  const appearance = page.getByRole('menuitem', { name: /Appearance/ })
  await appearance.focus()
  await appearance.press('ArrowRight')
  await expect(page.getByRole('menuitem', { name: 'Light', exact: true })).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(account).toBeFocused()
  await expect(page.getByRole('dialog', { name: 'Navigation', exact: true })).toHaveCount(0)
})

for (const [breakpoint, width] of [['md', 768], ['lg', 1024]]) {
  test(`open navigation releases the page at ${breakpoint}`, async ({ page, baseURL }) => {
    await openStory(page, 'dashboard-sidebarlayout--desktop', 'light', { width: 390, height: 844 }, baseURL)
    const url = new URL(page.url())
    url.searchParams.set('args', `hideBelow:${breakpoint}`)
    await page.goto(url.href)
    await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
    await expect(page.getByRole('dialog', { name: 'Navigation', exact: true })).toBeVisible()
    await page.setViewportSize({ width, height: 900 })
    await expect(page.getByRole('dialog', { name: 'Navigation', exact: true })).toHaveCount(0)
    await expect(page.locator('body')).not.toHaveAttribute('data-scroll-locked')
    expect(await page.locator('body').evaluate(node => getComputedStyle(node).pointerEvents)).not.toBe('none')
    await page.route('**/vault', route => route.fulfill({ contentType: 'text/html', body: '<h1>Vault destination</h1>' }))
    await page.getByRole('link', { name: 'Vault', exact: true }).click()
    await expect(page.getByRole('heading', { name: 'Vault destination' })).toBeVisible()
  })
}
