export {
  type ChatSession,
  sessionAtom,
  connectSession,
  disconnectSession,
} from './session-store';

export {
  activeSessionsAtom,
  registerActiveSession,
  unregisterActiveSession,
  setForegroundActiveSession,
  updateActiveSessionMeta,
  setActiveSessionConnection,
  setActiveSessionRunning,
  setActiveSessionAttention,
  setActiveSessionError,
  bumpActiveSessionActivity,
  resetActiveSessions,
  getAllActiveSessions,
  getActiveSession,
  getSessionsForProject,
  getSessionsForNavbar,
  getSessionsByActivity,
  getTotalRunningSessionCount,
  hasBackgroundRunningSessions,
  getAllProjectActivity,
  useActiveSessionsState,
  useActiveSessions,
  useActiveSession,
  useProjectSessions,
  useNavbarSessions,
  useSessionsByActivity,
  useProjectActivity,
  useTotalRunningSessions,
  useHasBackgroundRunningSessions,
} from './active-sessions-store';
export type {
  SessionProjectKey,
  ActiveSessionStatus,
  ActiveSessionReconnectState,
  ActiveSessionConnectionState,
  ActiveSessionTransportMode,
  ActiveSessionRecord,
  ActiveSessionsState,
  RegisterActiveSessionOptions,
  ActiveSessionConnectionOptions,
  ActiveSessionActivityOptions,
  ActiveProjectActivity,
} from './active-sessions-store';

export {
  messagesAtom,
  partMapAtom,
  isStreamingAtom,
  addMessage,
  addParts,
  updatePart,
  clearChat,
} from './chat-store';
