export {
  FileArtifactPane,
  type FileArtifactPaneProps,
  type FileFormat,
  type FileNode,
  FilePreview,
  type FilePreviewProps,
  type FileTabData,
  FileTabs,
  type FileTabsProps,
  FileTree,
  type FileTreeProps,
  type FileTreeVisibilityOptions,
  RichFileTree,
  type RichFileTreeGitEntry,
  type RichFileTreeGitStatus,
  type RichFileTreeProps,
  type RichFileTreeThemeVars,
  detectFileFormat,
  fileExtension,
  filterFileTree,
  getCodeLanguage,
  getFormatLabel,
  getSyntaxLanguage,
} from "@tangle-network/ui/files";
